import type {
  AppNotification,
  BloodRequest,
  InventoryRow,
  MatchCandidate,
} from "./types";

export const CURRENT_USER = {
  requester: { name: "Ananya Rao", org: "Family / patient advocate", location: "Indiranagar, Bengaluru" },
  donor: { name: "Rohit Menon", bloodGroup: "O-" as const, location: "Koramangala, Bengaluru" },
  bank: { name: "Sanjeevani Blood Centre", location: "Jayanagar, Bengaluru" },
};

export const REQUESTS: BloodRequest[] = [
  {
    id: "req-201",
    patientName: "Meera Rao",
    bloodGroup: "A+",
    units: 3,
    unitsSecured: 1,
    hospital: "Manipal Hospital, Old Airport Rd",
    location: "HAL, Bengaluru",
    urgency: "critical",
    requiredBy: "Today, 6:00 PM",
    createdAt: "12 min ago",
    status: "matching",
    note: "Post-surgical bleeding, ICU. Blood needed before evening rounds.",
  },
  {
    id: "req-202",
    patientName: "Imran Khan",
    bloodGroup: "O-",
    units: 2,
    unitsSecured: 2,
    hospital: "Narayana Health City",
    location: "Bommasandra, Bengaluru",
    urgency: "urgent",
    requiredBy: "Tomorrow, 9:00 AM",
    createdAt: "2 hours ago",
    status: "en_route",
    note: "Scheduled transfusion for thalassemia.",
    source: { name: "Rohit Menon", kind: "donor" },
  },
  {
    id: "req-203",
    patientName: "Lakshmi S.",
    bloodGroup: "B+",
    units: 1,
    unitsSecured: 1,
    hospital: "Fortis, Bannerghatta",
    location: "Bannerghatta, Bengaluru",
    urgency: "routine",
    requiredBy: "18 Sep, 11:00 AM",
    createdAt: "Yesterday",
    status: "fulfilled",
    source: { name: "Sanjeevani Blood Centre", kind: "bank" },
  },
];

export const CANDIDATES: MatchCandidate[] = [
  {
    id: "cand-1",
    kind: "bank",
    name: "Sanjeevani Blood Centre",
    bloodGroup: "A+",
    distanceKm: 3.2,
    etaMin: 18,
    eligible: true,
    unitsAvailable: 12,
    verified: true,
    rating: 4.8,
  },
  {
    id: "cand-2",
    kind: "donor",
    name: "Rohit Menon",
    bloodGroup: "O-",
    distanceKm: 2.1,
    etaMin: 14,
    eligible: true,
    lastDonation: "4 months ago",
    responseRate: 0.94,
    rating: 4.9,
    verified: true,
  },
  {
    id: "cand-3",
    kind: "donor",
    name: "Priya Nair",
    bloodGroup: "A+",
    distanceKm: 5.6,
    etaMin: 26,
    eligible: true,
    lastDonation: "7 months ago",
    responseRate: 0.88,
    rating: 4.7,
  },
  {
    id: "cand-4",
    kind: "bank",
    name: "Red Cross Blood Bank, MG Rd",
    bloodGroup: "A+",
    distanceKm: 8.9,
    etaMin: 34,
    eligible: true,
    unitsAvailable: 3,
    verified: true,
    rating: 4.5,
  },
  {
    id: "cand-5",
    kind: "donor",
    name: "Karthik Iyer",
    bloodGroup: "O+",
    distanceKm: 4.0,
    etaMin: 22,
    eligible: false,
    eligibleNote: "Donated 6 weeks ago — eligible in 6 weeks",
    lastDonation: "6 weeks ago",
    responseRate: 0.79,
    rating: 4.6,
  },
  {
    id: "cand-6",
    kind: "donor",
    name: "Sneha Gupta",
    bloodGroup: "A-",
    distanceKm: 11.4,
    etaMin: 41,
    eligible: true,
    lastDonation: "1 year ago",
    responseRate: 0.82,
    rating: 4.4,
  },
];

export const INVENTORY: InventoryRow[] = [
  { group: "O-", units: 4, reserved: 2, nearExpiry: 1, capacity: 20 },
  { group: "O+", units: 22, reserved: 3, nearExpiry: 0, capacity: 30 },
  { group: "A-", units: 6, reserved: 1, nearExpiry: 2, capacity: 20 },
  { group: "A+", units: 18, reserved: 4, nearExpiry: 3, capacity: 30 },
  { group: "B-", units: 3, reserved: 0, nearExpiry: 0, capacity: 20 },
  { group: "B+", units: 14, reserved: 2, nearExpiry: 1, capacity: 25 },
  { group: "AB-", units: 1, reserved: 0, nearExpiry: 0, capacity: 15 },
  { group: "AB+", units: 9, reserved: 1, nearExpiry: 0, capacity: 15 },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    role: "donor",
    kind: "emergency",
    title: "Critical: A+ needed 2.1 km away",
    body: "Manipal Hospital · 3 units · required by 6:00 PM today.",
    time: "12 min ago",
    unread: true,
  },
  {
    id: "n2",
    role: "requester",
    kind: "status",
    title: "Rohit Menon accepted your request",
    body: "O- donor is en route to Narayana Health City. ETA 14 min.",
    time: "36 min ago",
    unread: true,
  },
  {
    id: "n3",
    role: "bank",
    kind: "reminder",
    title: "3 units A+ nearing expiry",
    body: "Expiring within 5 days. Prioritise for upcoming requests.",
    time: "1 hour ago",
    unread: true,
  },
  {
    id: "n4",
    role: "requester",
    kind: "status",
    title: "Request fulfilled — Lakshmi S.",
    body: "1 unit B+ confirmed from Sanjeevani Blood Centre.",
    time: "Yesterday",
    unread: false,
  },
  {
    id: "n5",
    role: "donor",
    kind: "reminder",
    title: "You're eligible to donate again",
    body: "It's been 3 months since your last donation. Turn on availability?",
    time: "2 days ago",
    unread: false,
  },
];

export const INCOMING_QUEUE: BloodRequest[] = [
  {
    id: "req-301",
    patientName: "Arjun Deshpande",
    bloodGroup: "O-",
    units: 2,
    unitsSecured: 0,
    hospital: "St. John's Medical College",
    location: "Koramangala, Bengaluru",
    urgency: "critical",
    requiredBy: "Today, 4:30 PM",
    createdAt: "5 min ago",
    status: "matching",
    note: "Road accident, trauma unit.",
  },
  {
    id: "req-302",
    patientName: "Fatima Sheikh",
    bloodGroup: "B+",
    units: 4,
    unitsSecured: 1,
    hospital: "Apollo, Sheshadripuram",
    location: "Sheshadripuram, Bengaluru",
    urgency: "urgent",
    requiredBy: "Today, 8:00 PM",
    createdAt: "40 min ago",
    status: "matching",
  },
  {
    id: "req-303",
    patientName: "Deepak Rana",
    bloodGroup: "AB+",
    units: 1,
    unitsSecured: 0,
    hospital: "Columbia Asia, Hebbal",
    location: "Hebbal, Bengaluru",
    urgency: "routine",
    requiredBy: "19 Sep, 10:00 AM",
    createdAt: "3 hours ago",
    status: "matching",
  },
];

export const DONOR_HISTORY = [
  { id: "d1", date: "12 May 2026", location: "Sanjeevani Blood Centre", group: "O-", units: 1, recipient: "Emergency pool" },
  { id: "d2", date: "8 Jan 2026", location: "Red Cross, MG Rd", group: "O-", units: 1, recipient: "Meera K. (A+)" },
  { id: "d3", date: "20 Sep 2025", location: "Narayana Health City", group: "O-", units: 1, recipient: "Emergency pool" },
];
